version: '3.9'

services:

  jenkins:
    build:
      context: ./jenkins
    ports:
      - "5555:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
#      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          memory: 3G
    restart: always

  sonarqube:
    user: 1004:1004
    image: sonarqube:8.9.2-community
    ports:
      - "9000:9000"
#    volumes:
#      - sonarqube_conf:/opt/sonarqube/conf
#      - sonarqube_data:/opt/sonarqube/data
#      - sonarqube_extensions:/opt/sonarqube/extensions
#      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    deploy:
      resources:
        limits:
          memory: 350M
    restart: always

volumes:
  jenkins_home:
#  sonarqube_conf:
#  sonarqube_data:
#  sonarqube_extensions:
#  sonarqube_bundled-plugins:
#  jenkins_data: