version: '3.9'

services:

  jenkins:
    build:
      context: ./jenkins
    ports:
      - "5555:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
#      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          memory: 3G
    restart: always

volumes:
  jenkins_home: