version: '3.9'

services:

  jenkins:
    build:
      context: ./jenkins
    ports:
      - "5555:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
#      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          memory: 3G
    restart: always

  sonarqube:
    user: 1004:1004
    image: sonarqube:8.9.2-community
    ports:
      - "9000:9000"
#    volumes:
#      - sonarqube_conf:/opt/sonarqube/conf
#      - sonarqube_data:/opt/sonarqube/data
#      - sonarqube_extensions:/opt/sonarqube/extensions
#      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    deploy:
      resources:
        limits:
          memory: 350M
    restart: always

  mongo:
    image: mongo:5.0.2
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    deploy:
      resources:
        limits:
          memory: 700M
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Honda12345*
      MONGO_INITDB_DATABASE: my-database

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    deploy:
      resources:
        limits:
          memory: 350M
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: Honda12345*
      ME_CONFIG_MONGODB_URL: mongodb://admin:Honda12345*@mongo:27017/

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      resources:
        limits:
          memory: 350M
    restart: always

volumes:
  jenkins_home:
#  jenkins_data:
  mongodb_data:
#  sonarqube_conf:
#  sonarqube_data:
#  sonarqube_extensions:
#  sonarqube_bundled-plugins: